name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: pwsh

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.11.1
        with:
          use-github-auto-merge: true

  build-and-test:
    name: build-and-test on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Setup Dependency Caching
      uses: actions/cache@v4
      id: nuget-cache
      with:
        path: |
          ~/.nuget/packages
          ${{ github.workspace }}/**/obj/project.assets.json
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -p:ContinuousIntegrationBuild=True --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal --logger GitHubActions --
        RunConfiguration.CollectSourceInformation=true
