name: Copilot Setup Steps

on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  copilot-setup-steps:
    name: copilot-setup-steps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.x
    - name: Setup Dependency Caching
      uses: actions/cache@v4
      id: nuget-cache
      with:
        path: |
          ~/.nuget/packages
          ${{ github.workspace }}/**/obj/project.assets.json
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore